# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-16 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190513_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='favicon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
